//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Lateetud.NServiceBus.Subscriber.CenturySuretyProcess1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CenturysuretyProcessSoapBinding", Namespace="urn:blueprism:webservice:centurysuretyprocess")]
    public partial class CenturysuretyProcessService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CenturysuretyProcessOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CenturysuretyProcessService() {
            this.Url = global::Lateetud.NServiceBus.Subscriber.Properties.Settings.Default.Lateetud_NServiceBus_Subscriber_CenturySuretyProcess1_CenturysuretyProcessService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CenturysuretyProcessCompletedEventHandler CenturysuretyProcessCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:blueprism:webservice:centurysuretyprocess", ResponseNamespace="urn:blueprism:webservice:centurysuretyprocess")]
        [return: System.Xml.Serialization.SoapElementAttribute("Status")]
        public string CenturysuretyProcess(string Input) {
            object[] results = this.Invoke("CenturysuretyProcess", new object[] {
                        Input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CenturysuretyProcessAsync(string Input) {
            this.CenturysuretyProcessAsync(Input, null);
        }
        
        /// <remarks/>
        public void CenturysuretyProcessAsync(string Input, object userState) {
            if ((this.CenturysuretyProcessOperationCompleted == null)) {
                this.CenturysuretyProcessOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCenturysuretyProcessOperationCompleted);
            }
            this.InvokeAsync("CenturysuretyProcess", new object[] {
                        Input}, this.CenturysuretyProcessOperationCompleted, userState);
        }
        
        private void OnCenturysuretyProcessOperationCompleted(object arg) {
            if ((this.CenturysuretyProcessCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CenturysuretyProcessCompleted(this, new CenturysuretyProcessCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void CenturysuretyProcessCompletedEventHandler(object sender, CenturysuretyProcessCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CenturysuretyProcessCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CenturysuretyProcessCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591